import { Geist, Geist_Mono, Inconsolata } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { SanityLive } from "@/sanity/lib/live";

const inconsolata = Inconsolata({ 
  subsets: ["latin"], 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inconsolata.className}
      >
        <Navbar />
        <div className="max-w-5xl mx-auto px-4">
          {children}
          <SanityLive />
        </div>
      </body>
    </html>
  );
}
